<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Devil-Machine" name="testCases.UserDetailsPageTest" tests="1" failures="1" timestamp="7 Feb 2022 13:11:07 GMT" time="7.984" errors="0">
  <testcase name="BookingCompletionTest" time="7.984" classname="testCases.UserDetailsPageTest">
    <failure type="java.lang.AssertionError" message="Unable to navigate to Booking page expected [Booking Confirm] but found [Page not found at /rent/75]">
      <![CDATA[java.lang.AssertionError: Unable to navigate to Booking page expected [Booking Confirm] but found [Page not found at /rent/75]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at testCases.UserDetailsPageTest.BookingCompletionTest(UserDetailsPageTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- BookingCompletionTest -->
</testsuite> <!-- testCases.UserDetailsPageTest -->
